### ISSUE TITLE
ObjectMapper in DispatcherWebscript

### ISSUE THREAD

**Issue by dgradecak** [dgradecak/alfresco-mvc#10]
as the object mapper (jackson 2) is used to encode json in case of unhandled exceptions, we have an issue with older versions of Alfresco, where only jackson 1 is used. Since we rely on jackson 2 we better simply encode the json string into a java string directly.

However, Alfresco 5 includes jackson 2 also and therfore we might have the same approach for older Alfresco versions.

**Comment by lorelj2** [comment]
Solved in #11
